Object.defineProperty(exports,"__esModule",{value:true});
var SHOW_USER_LOGIN=exports.SHOW_USER_LOGIN='SHOW_USER_LOGIN';
var ON_LOGIN=exports.ON_LOGIN='ON_LOGIN';
var SHOW_USER_SIGNUP=exports.SHOW_USER_SIGNUP='SHOW_USER_SIGNUP';
var ON_USER_REGISTER=exports.ON_USER_REGISTER='ON_USER_REGISTER';
var SHOW_USER_LOGOUT=exports.SHOW_USER_LOGOUT='SHOW_USER_LOGOUT';
var ON_USER_LOGOUT=exports.ON_USER_LOGOUT='ON_USER_LOGOUT';
var SHOW_USER_PROFILE=exports.SHOW_USER_PROFILE='SHOW_USER_PROFILE';
var ON_USER_PROFILE=exports.ON_USER_PROFILE='ON_USER_PROFILE';






var SHOW_ALL_BOOKS=exports.SHOW_ALL_BOOKS='SHOW_ALL_BOOKS';
var SHOW_MY_LIBRARY=exports.SHOW_MY_LIBRARY='SHOW_MY_LIBRARY';



var NAVIGATION_FORWARD=exports.NAVIGATION_FORWARD='NAVIGATION_FORWARD';
var NAVIGATION_PUSH=exports.NAVIGATION_PUSH='NAVIGATION_PUSH';
var NAVIGATION_POP=exports.NAVIGATION_POP='NAVIGATION_POP';
var NAVIGATION_BACK=exports.NAVIGATION_BACK='NAVIGATION_BACK';