

//   User Management  // 
export const ON_LOGIN = 'ON_LOGIN'
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
export const ON_LOGIN_FAIL = 'ON_LOGIN_FAIL'

export const ON_USER_REGISTER = 'ON_USER_REGISTER'
export const ON_REGISTER_SUCCESS = 'ON_REGISTER_SUCCESS'
export const ON_REGISTER_FAIL = 'ON_REGISTER_FAIL'

export const ON_USER_LOGOUT = 'ON_USER_LOGOUT'
export const ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS'
export const ON_LOGOUT_FAIL = 'ON_LOGOUT_FAIL' 
 




// Book Management
export const ON_BOOK_LIST = 'ON_BOOK_LIST'
export const ON_BOOK_LIST_SUCCESS = 'ON_BOOK_LIST_SUCCESS' 
export const ON_BOOK_LIST_FAIL = 'ON_BOOK_LIST_FAIL' 

// Navigation
//export const SET_TAB = 'SET_TAB'
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH'
export const NAVIGATION_POP = 'NAVIGATION_POP'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'
export const NAVIGATION_UPDATE = 'NAVIGATION_UPDATE'